// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "samclick": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/kasoshojo/api/design
// --out=$(GOPATH)src/github.com/kasoshojo/api
// --version=v1.2.0-dirty

package test
